services:
  - type: web
    name: afrimail-pro
    env: python
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate
    startCommand: gunicorn afrimail.wsgi:application
    envVars:
      - key: DEBUG
        value: False
      - key: DJANGO_SETTINGS_MODULE
        value: afrimail.settings
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: afrimail-db
          property: connectionString

  - type: worker
    name: afrimail-celery-worker
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: celery -A afrimail worker --loglevel=info
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: afrimail.settings

  - type: worker
    name: afrimail-celery-beat
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: celery -A afrimail beat --loglevel=info
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: afrimail.settings

databases:
  - name: afrimail-db
    databaseName: afrimail_production
    user: afrimail_user

  - name: afrimail-redis
    plan: starter